env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "next"
  - google
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  camelcase: off
  linebreak-style: off
  object-curly-spacing:
    - error
    - "always"
  require-jsdoc: off
  semi: ["error", "never"]
  no-invalid-this: off
  max-len:
    - error
    - ignoreStrings: true